/* Automatically generated by po2tbl.sed from qronos.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Error: %s don't exist.\n", 2},
  {"Error: the euid must be the %s uid.\n", 3},
  {"\
    Qronos version %s, Copyright (C) 1999 Sergio Gómez <sergio@cartero.com>\n\
    Qronos comes with ABSOLUTELY NO WARRANTY; for details read the GPL.\n\
    This is free software, and you are welcome to redistribute it under \n\
    certain conditions.\n\
\n", 4},
  {"Service unavailable, try again in %d %s.\n", 5},
  {"minutes", 6},
  {"minute", 7},
  {"Permission denied.\n", 8},
  {"Service unavailable, try again later.\n", 9},
  {"\
An error had been happen while executing the program. Please contact with \
your System Administrator.\n", 10},
};

int _msg_tbl_length = 10;
